//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jqGridAddEditDelete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.UnitGalleries = new HashSet<UnitGallery>();
        }
    
        public int UnitId { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int Bed { get; set; }
        public double Bathroom { get; set; }
        public double SquareFoot { get; set; }
        public int YearBuilt { get; set; }
        public string Description { get; set; }
        public string PrimaryPhoto { get; set; }
    
        public virtual ICollection<UnitGallery> UnitGalleries { get; set; }
    }
}
